# Setup
title:        Hafizur Rahman
tagline:      Aspiring Data Scientist/Software Architect
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Hafizur Rahman 
  mail:       bibagimon (at) gmail

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
